/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ddosattackdetection;

import Database.Database;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.Random;
import java.util.StringTokenizer;


public class Agents extends javax.swing.JFrame {

    /**
     * Creates new form Agents
     */
    public Agents() {
        initComponents();
        
        	Thread t = new Thread(new PortListener(2001));
				t.setName("Listener-" + "2001");
				t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENTS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("AGENTS 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 130, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 260, 210));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 260, 210));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 260, 210));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("AGENTS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 310, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("AGENTS 1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("AGENTS 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 130, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 90, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }
    
    public double GetValue(double min,double max)
    {
        Random r=new Random();
        return  Math.round((r.nextDouble() * (max - min ) + min) * 100.0) / 100.0;
        
        
    }
    
     class PortListener implements Runnable {
	   	
		   		BufferedOutputStream bos = null;
		   		LinkedList ll = new LinkedList();
		   		ServerSocket server;
		   		Socket connection;
		   		BufferedReader br = null;
		   		int port;

		   		public PortListener(int port) {
		   			this.port = port;
		   		}

		   		public void run() {
		   			
		   			try { 
		   			
		   				    server = new ServerSocket(2001);
		   					
		   				     while (true)
		   				   {
		   					                   connection = server.accept();
		   					
		   					                   br = new BufferedReader(
		   							           new InputStreamReader(new BufferedInputStream(
		   									   connection.getInputStream())));
		   					
		   					                      String strLine;
		   					                    
		   					                   StringBuffer buffer = new StringBuffer();
		   					                
		   					                   while ((strLine = br.readLine()) != null)
		   					                  {
		   						                 
		   						                   System.out.println(strLine);
		   						                   buffer.append(strLine);
                                                                                   
                                                                                   

		  			                   }
		   				                               	br.close();
		   					                            connection.close();
		   					                           
		   					                 
		   			                           
		   					                         StringTokenizer st1 = new StringTokenizer(buffer.toString(),"^");
            while(st1.hasMoreTokens())
            {
              ll.add(st1.nextToken());
             
            }
 
           jTextArea2.append("Data :"+ll.get(1).toString());
                 jTextArea2.append("\n");
                 GenerateRecords(ll.get(0).toString(),ll.get(1).toString(),"1");
          Thread.sleep(2000);
                jTextArea3.append("Data :"+ll.get(1).toString());
                 jTextArea3.append("\n");
                     GenerateRecords(ll.get(0).toString(),ll.get(1).toString(),"2");
           Thread.sleep(2000);
                     jTextArea4.append("Data :"+ll.get(1).toString());
                      jTextArea4.append("\n");
                        GenerateRecords(ll.get(0).toString(),ll.get(1).toString(),"3");
                    Thread.sleep(2000);
             GenerateRecords(ll.get(0).toString(),ll.get(1).toString(),"4");
                    Thread.sleep(2000);
             GenerateRecords(ll.get(0).toString(),ll.get(1).toString(),"5");
                                              Connection con=null;
    Statement st=null;
    ResultSet rs=null;

		   	
   Socket skt;
    skt = new Socket("127.1.1.1",2002);
      
         System.out.print("Server has connected!\n" + buffer.toString());
         PrintWriter out = new PrintWriter(skt.getOutputStream(), true);
   System.out.print("Agent\n" + buffer.toString());
         out.print(buffer.toString());
          
         out.close();
         skt.close();
ll.clear();
                                }
                                        }
		   			           catch (Exception e)
		   			            {
		   			        	   
		   			             }   
		   			           finally
		   			           {
		   			        	   
		   			            }
		   			

		}
     }
     
      public void GenerateRecords(String type,String data,String time) throws SQLException
    {
                   Double FlowLength=0.0;
             Double FlowDuration=0.0;
              Double FlowSize=0.0;
               Double FlowRatio=0.0;
            


     
               if(type.equals("withoutDDOS"))
               {
                  FlowLength= GetValue(0.35,0.4);
                   FlowDuration= GetValue(0.4,0.45);
                   FlowSize= GetValue(0.35, 0.5);
                   FlowRatio= GetValue(0.35,0.45);
               }
               else
               {
                    FlowLength= GetValue(0.5,0.65);
                   FlowDuration= GetValue(0.5,0.55);
                   FlowSize= GetValue(0.6,0.75);
                   FlowRatio= GetValue(0.58,0.65);
               }
    double[] x= {FlowLength,FlowDuration,FlowSize,FlowRatio};
               int[] y={1,2,3,4,5};
        try
        {
            KNN.learn(x, y, Integer.parseInt(time));
        }
        catch(Exception ex)
        {
            
        }

		Connection con = Database.getconnection();
  PreparedStatement pst=con.prepareStatement("insert into results(Type, FlowLength, FlowDuration, FlowSize, FlowRatio,Time)values(?,?,?,?,?,?)");
                     
			pst.setString(1,type);
	                pst.setString(2,FlowLength.toString());
                         pst.setString(3,FlowDuration.toString());
                         pst.setString(4,FlowSize.toString());
                         pst.setString(5,FlowRatio.toString());
                         pst.setString(6,time);
                         int l=pst.executeUpdate();
        
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
