/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ddosattackdetection;

import Database.Database;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;


public class TrafficGeneration extends javax.swing.JFrame {

    /**
     * Creates new form TrafficGeneration
     */
    public TrafficGeneration() {
        initComponents();
        
        Thread t = new Thread(new TrafficGeneration.PortListener(2003));
				t.setName("Listener-" + "2003");
				t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRAFFIC GENERATOR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("DDOS Detection");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 310, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable2);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 440, 100));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("TRAFFIC INFORMATION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 310, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 260, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 90, 400));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("RESULT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Results rs=new Results();
        rs.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficGeneration().setVisible(true);
            }
        });
    }
    
       class PortListener implements Runnable {
		   	
		   		BufferedOutputStream bos = null;
		   		LinkedList ll = new LinkedList();
		   		ServerSocket server;
		   		Socket connection;
		   		BufferedReader br = null;
		   		int port;

		   		public PortListener(int port) {
		   			this.port = port;
		   		}

		   		public void run() {
		   			
		   			try { 
		   			
		   				    server = new ServerSocket(2003);
		   					
		   				     while (true)
		   				   {
		   					                   connection = server.accept();
		   					
		   					                   br = new BufferedReader(
		   							           new InputStreamReader(new BufferedInputStream(
		   									   connection.getInputStream())));
		   					
		   					                      String strLine;
		   					                    
		   					                   StringBuffer buffer = new StringBuffer();
		   					                
		   					                   while ((strLine = br.readLine()) != null)
		   					                  {
		   						                 
		   						                   System.out.println(strLine);
		   						                   buffer.append(strLine);

		  			                   }
		   				                               	br.close();
		   					                            connection.close();
		   					                           
		   					                 
		   			                           
		   					                         StringTokenizer st1 = new StringTokenizer(buffer.toString(),"^");
            while(st1.hasMoreTokens())
            {
              ll.add(st1.nextToken());
             
              
            }
          Thread.sleep(2000);
                                              Connection con=null;
    Statement st=null;
    ResultSet rs=null;
     Double FlowLength=0.0;
             Double FlowDuration=0.0;
              Double FlowSize=0.0;
               Double FlowRatio=0.0;
    if(ll.size() > 0)
    {
      DefaultTableModel   dtm = new DefaultTableModel();
    dtm.setColumnIdentifiers(new Object[]{"Flow Length", "Flow Duration", "Flow Size","Flow Ratio","Time"});
    jTable2.setModel(dtm);
    try {
          Connection con1=null;
    Statement st2=null;
    ResultSet rs1=null;
  
			 con1 = Database.getconnection();
 st2 = con1.createStatement();
rs1=st2.executeQuery("select FlowLength, FlowDuration, FlowSize, FlowRatio, Time from results");
			  while (rs1.next()) 
			{
            dtm.addRow(new Object[]{rs1.getString("FlowLength"), rs1.getString("FlowDuration"), rs1.getString("FlowSize"),rs1.getString("FlowRatio"),rs1.getString("Time")});
            
                  FlowLength=  Double.parseDouble(rs1.getString("FlowLength"));
                  FlowDuration=  Double.parseDouble(rs1.getString("FlowDuration"));
                  FlowSize=  Double.parseDouble(rs1.getString("FlowSize"));
                   FlowRatio= Double.parseDouble(rs1.getString("FlowRatio"));
        }
    }
        catch(Exception ex)
        {
            
        }
    }
    
    if(FlowLength > 0.49 && FlowLength > 0.49 && FlowLength > 0.49 && FlowLength > 0.49)
    {
    
  jTextArea1.append("Result : DDOS Attack Found");
  jTextArea1.append("\n");
    }
    else
    {
         jTextArea1.append("Result : DDOS Attack Not Found");
  jTextArea1.append("\n"); 
        
    }
   
			// con = Database.getconnection();
 // PreparedStatement pst=con.prepareStatement("insert into recovery(FileName,RPO,FilePath)values(?,?,?)");
                     
			//pst.setString(1,ll.get(3).toString());
	               // pst.setString(2,ll.get(1).toString());
                       //  pst.setString(3,ll.get(2).toString());
                        // int l=pst.executeUpdate();
		   	

 System.out.print("TrafficGenerated!\n");
  System.out.print(buffer.toString());

                                }
                                        }
		   			           catch (Exception e)
		   			            {
		   			        	   
		   			             }   
		   			           finally
		   			           {
		   			        	   
		   			            }
		   			

		}
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
